components:
  examples:
    json_400_panui_mgmt_bad_xpath:
      summary: Bad XPath
      value:
        _errors:
        - code: E013
          details: {}
          message: Bad XPath
        _request_id: abcd-1234
    json_400_panui_mgmt_invalid_command:
      summary: Invalid Command
      value:
        _errors:
        - code: E003
          details: {}
          message: Invalid Command
        _request_id: abcd-1234
    json_400_panui_mgmt_invalid_object:
      summary: Invalid Object
      value:
        _errors:
        - code: E003
          details: {}
          message: Invalid Object
        _request_id: abcd-1234
    json_400_panui_mgmt_malformed_command:
      summary: Malformed Command
      value:
        _errors:
        - code: E003
          details: {}
          message: Malformed Command
        _request_id: abcd-1234
    json_400_panui_restapi_input_format_mismatch:
      summary: Input Format Mismatch
      value:
        _errors:
        - code: E003
          details: {}
          message: 'Input Format Mismatch: input-format=json'
        _request_id: abcd-1234
    json_400_panui_restapi_invalid_query_parameter:
      summary: Invalid Query Parameter
      value:
        _errors:
        - code: E003
          details: {}
          message: 'Invalid Query Parameter: location=invalid'
        _request_id: abcd-1234
    json_400_panui_restapi_missing_body:
      summary: Missing Body
      value:
        _errors:
        - code: E003
          details: {}
          message: Missing Body
        _request_id: abcd-1234
    json_400_panui_restapi_missing_query_parameter:
      summary: Missing Query Parameter
      value:
        _errors:
        - code: E003
          details: {}
          message: 'Missing Query Parameter: name'
        _request_id: abcd-1234
    json_400_panui_restapi_output_format_mismatch:
      summary: Output Format Mismatch
      value:
        _errors:
        - code: E003
          details: {}
          message: 'Output Format Mismatch: output-format=json Accept=xml'
        _request_id: abcd-1234
    json_401_panui_auth_invalid_credential:
      summary: Invalid Credential
      value:
        _errors:
        - code: E016
          details: {}
          message: Invalid Credential
        _request_id: abcd-1234
    json_401_panui_auth_key_expired:
      summary: Key Expired
      value:
        _errors:
        - code: E016
          details: {}
          message: Key Expired
        _request_id: abcd-1234
    json_401_panui_auth_key_too_long:
      summary: Key Too Long
      value:
        _errors:
        - code: E016
          details: {}
          message: Key Too Long
        _request_id: abcd-1234
    json_401_panui_auth_need_password_change:
      summary: Need Password Change
      value:
        _errors:
        - code: E016
          details: {}
          message: The password needs to be changed.
        _request_id: abcd-1234
    json_401_panui_auth_not_authenticated:
      summary: Not Authenticated
      value:
        _errors:
        - code: E016
          details: {}
          message: Not Authenticated
        _request_id: abcd-1234
    json_403_panui_auth_unauthorized:
      summary: Unauthorized
      value:
        _errors:
        - code: E007
          details: {}
          message: Unauthorized
        _request_id: abcd-1234
    json_404_panui_mgmt_object_not_present:
      summary: Object Not Present
      value:
        _errors:
        - code: E005
          details: {}
          message: Object Not Present
        _request_id: abcd-1234
    json_405_panui_restapi_action_not_supported:
      summary: Action Not Supported
      value:
        _errors:
        - code: E012
          details: {}
          message: 'Action Not Supported: move'
        _request_id: abcd-1234
    json_409_panui_mgmt_name_not_unique:
      summary: Name Not Unique
      value:
        _errors:
        - code: E006
          details: {}
          message: Name Not Unique
        _request_id: abcd-1234
    json_409_panui_mgmt_object_not_unique:
      summary: Object Not Unique
      value:
        _errors:
        - code: E016
          details: {}
          message: Object Not Unique
        _request_id: abcd-1234
    json_409_panui_mgmt_reference_not_zero:
      summary: Reference Not Zero
      value:
        _errors:
        - code: E009
          details: {}
          message: Reference Not Zero
        _request_id: abcd-1234
    json_501_panui_restapi_method_not_supported:
      summary: Method Not Supported
      value:
        _errors:
        - code: E012
          details: {}
          message: Method Not Supported
        _request_id: abcd-1234
    json_501_panui_restapi_version_not_supported:
      summary: Version Not Supported
      value:
        _errors:
        - code: E012
          details: {}
          message: Version Not Supported
        _request_id: abcd-1234
    json_504_panui_mgmt_session_timeout:
      summary: Session Timeout
      value:
        _errors:
        - code: 4
          details: {}
          message: Session Timeout
        _request_id: abcd-1234
  parameters:
    folder:
      description: 'The folder on which you want to perform this operation.

        '
      in: query
      name: folder
      required: true
      schema:
        enum:
        - Shared
        - Mobile Users
        - Remote Networks
        - Service Connections
        - Mobile Users Container
        - Mobile Users Explicit Proxy
        type: string
    limit-optional:
      description: 'The maximum number of result objects to return per page.

        '
      in: query
      name: limit
      required: false
      schema:
        type: number
    name-optional:
      description: 'The name of the entry.

        '
      in: query
      name: name
      required: false
      schema:
        type: string
    offset-optional:
      description: 'The offset of the result entry.

        '
      in: query
      name: offset
      required: false
      schema:
        type: number
    position:
      description: 'The position of a security rule

        '
      in: query
      name: position
      required: true
      schema:
        default: pre
        enum:
        - pre
        - post
        type: string
    uuid-required:
      description: 'The resource''s unique identifier.

        '
      in: path
      name: id
      required: true
      schema:
        type: string
  responses:
    access_errors:
      content:
        application/json:
          examples:
            auth_unauthorized:
              $ref: '#/components/examples/json_403_panui_auth_unauthorized'
          schema:
            $ref: '#/components/schemas/generic_error'
      description: Forbidden
    auth_errors:
      content:
        application/json:
          examples:
            auth_not_authenticated:
              $ref: '#/components/examples/json_401_panui_auth_not_authenticated'
            invalid_credential:
              $ref: '#/components/examples/json_401_panui_auth_invalid_credential'
            key_expired:
              $ref: '#/components/examples/json_401_panui_auth_key_expired'
            key_too_long:
              $ref: '#/components/examples/json_401_panui_auth_key_too_long'
            need_password_change:
              $ref: '#/components/examples/json_401_panui_auth_need_password_change'
          schema:
            $ref: '#/components/schemas/generic_error'
      description: Unauthorized
    bad_request_errors_basic:
      content:
        application/json:
          examples:
            input_format_mismatch:
              $ref: '#/components/examples/json_400_panui_restapi_input_format_mismatch'
            invalid_query_parameter:
              $ref: '#/components/examples/json_400_panui_restapi_invalid_query_parameter'
            missing_query_parameter:
              $ref: '#/components/examples/json_400_panui_restapi_missing_query_parameter'
            output_format_mismatch:
              $ref: '#/components/examples/json_400_panui_restapi_output_format_mismatch'
          schema:
            $ref: '#/components/schemas/generic_error'
      description: Bad Request
    bad_request_errors_basic_with_body:
      content:
        application/json:
          examples:
            input_format_mismatch:
              $ref: '#/components/examples/json_400_panui_restapi_input_format_mismatch'
            invalid_object:
              $ref: '#/components/examples/json_400_panui_mgmt_invalid_object'
            invalid_query_parameter:
              $ref: '#/components/examples/json_400_panui_restapi_invalid_query_parameter'
            missing_body:
              $ref: '#/components/examples/json_400_panui_restapi_missing_body'
            missing_query_parameter:
              $ref: '#/components/examples/json_400_panui_restapi_missing_query_parameter'
            output_format_mismatch:
              $ref: '#/components/examples/json_400_panui_restapi_output_format_mismatch'
          schema:
            $ref: '#/components/schemas/generic_error'
      description: Bad Request
    conflict_errors:
      content:
        application/json:
          examples:
            name_not_unique:
              $ref: '#/components/examples/json_409_panui_mgmt_name_not_unique'
            object_not_unique:
              $ref: '#/components/examples/json_409_panui_mgmt_object_not_unique'
            reference_not_zero:
              $ref: '#/components/examples/json_409_panui_mgmt_reference_not_zero'
          schema:
            $ref: '#/components/schemas/generic_error'
      description: Conflict
    default_errors:
      content:
        application/json:
          examples:
            action_not_supported:
              $ref: '#/components/examples/json_405_panui_restapi_action_not_supported'
            bad_xpath:
              $ref: '#/components/examples/json_400_panui_mgmt_bad_xpath'
            invalid_command:
              $ref: '#/components/examples/json_400_panui_mgmt_invalid_command'
            malformed_command:
              $ref: '#/components/examples/json_400_panui_mgmt_malformed_command'
            method_not_allowed:
              $ref: '#/components/examples/json_501_panui_restapi_method_not_supported'
            session_timeout:
              $ref: '#/components/examples/json_504_panui_mgmt_session_timeout'
            version_not_supported:
              $ref: '#/components/examples/json_501_panui_restapi_version_not_supported'
          schema:
            $ref: '#/components/schemas/generic_error'
      description: General Errors
    http_created:
      description: Created
    http_ok:
      description: Ok
    not_found:
      content:
        application/json:
          examples:
            object_not_present:
              $ref: '#/components/examples/json_404_panui_mgmt_object_not_present'
          schema:
            $ref: '#/components/schemas/generic_error'
      description: Not Found
  schemas:
    app-override-rules:
      properties:
        application:
          type: string
        description:
          maxLength: 1024
          type: string
        destination:
          default:
          - any
          items:
            type: string
          type: array
        disabled:
          default: false
          type: boolean
        from:
          default:
          - any
          items:
            type: string
          type: array
        group_tag:
          type: string
        id:
          description: uuid of the resource
          example: abcd-1234
          readOnly: true
          type: string
        name:
          maxLength: 63
          pattern: ^[a-zA-Z0-9._-]+$
          type: string
        negate_destination:
          default: false
          type: boolean
        negate_source:
          default: false
          type: boolean
        port:
          maximum: 65535
          minimum: 0
          type: integer
        protocol:
          enum:
          - tcp
          - udp
          type: string
        source:
          default:
          - any
          items:
            type: string
          type: array
        tag:
          items:
            type: string
          type: array
        to:
          default:
          - any
          items:
            type: string
          type: array
      required:
      - name
      - application
      - port
      - protocol
      - destination
      - from
      - source
      - to
      type: object
    error_detail_cause_info:
      properties:
        code:
          type: string
        details:
          type: object
        help:
          type: string
        message:
          type: string
      title: Cause Info
      type: object
    error_detail_cause_infos:
      items:
        $ref: '#/components/schemas/error_detail_cause_info'
      type: array
    generic_error:
      properties:
        _errors:
          $ref: '#/components/schemas/error_detail_cause_infos'
        _request_id:
          type: string
      type: object
  securitySchemes:
    Bearer:
      scheme: bearer
      type: http
info:
  contact: {}
  description: 'Manages application override rules.

    '
  title: Application Override Rules
  version: '1.0'
  x-logo:
    url: pan-logo.png
openapi: 3.0.0
paths:
  /sse/config/v1/app-override-rules:
    get:
      description: 'Retrieve a list of all [application](https://docs.paloaltonetworks.com/network-security/security-policy/objects/applications)
        override rules.

        '
      operationId: get-sse-config-v1-app-override-rules
      parameters:
      - $ref: '#/components/parameters/limit-optional'
      - $ref: '#/components/parameters/offset-optional'
      - $ref: '#/components/parameters/position'
      - $ref: '#/components/parameters/folder'
      - $ref: '#/components/parameters/name-optional'
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  data:
                    allOf:
                    - items:
                        $ref: '#/components/schemas/app-override-rules'
                      type: array
                  limit:
                    default: 200
                    type: number
                  offset:
                    default: 0
                    type: number
                  total:
                    type: number
                type: object
          description: List of application override policy rules
        '400':
          $ref: '#/components/responses/bad_request_errors_basic'
        '401':
          $ref: '#/components/responses/auth_errors'
        '403':
          $ref: '#/components/responses/access_errors'
        '404':
          $ref: '#/components/responses/not_found'
        default:
          $ref: '#/components/responses/default_errors'
      security:
      - Bearer: []
      summary: List all application override rules
      tags:
      - ApplicationOverrideRules
    post:
      description: 'Create an [application](https://docs.paloaltonetworks.com/network-security/security-policy/objects/applications)
        override rule.

        '
      operationId: post-sse-config-v1-app-override-rules
      parameters:
      - $ref: '#/components/parameters/position'
      - $ref: '#/components/parameters/folder'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/app-override-rules'
        description: The application override policy rule you want to create
      responses:
        '200':
          $ref: '#/components/responses/http_created'
        '400':
          $ref: '#/components/responses/bad_request_errors_basic_with_body'
        '401':
          $ref: '#/components/responses/auth_errors'
        '403':
          $ref: '#/components/responses/access_errors'
        '409':
          $ref: '#/components/responses/conflict_errors'
        default:
          $ref: '#/components/responses/default_errors'
      security:
      - Bearer: []
      summary: Create an application override rule
      tags:
      - ApplicationOverrideRules
  /sse/config/v1/app-override-rules/{id}:
    delete:
      description: 'Delete an [application](https://docs.paloaltonetworks.com/network-security/security-policy/objects/applications)
        override rule.

        '
      operationId: delete-sse-config-v1-app-override-rules-id
      parameters:
      - $ref: '#/components/parameters/uuid-required'
      responses:
        '200':
          $ref: '#/components/responses/http_ok'
        '400':
          $ref: '#/components/responses/bad_request_errors_basic'
        '401':
          $ref: '#/components/responses/auth_errors'
        '403':
          $ref: '#/components/responses/access_errors'
        '404':
          $ref: '#/components/responses/not_found'
        '409':
          $ref: '#/components/responses/conflict_errors'
        default:
          $ref: '#/components/responses/default_errors'
      security:
      - Bearer: []
      summary: Delete an application override rule
      tags:
      - ApplicationOverrideRules
    get:
      description: 'Get an [application](https://docs.paloaltonetworks.com/network-security/security-policy/objects/applications)
        override rule by ID.

        '
      operationId: get-sse-config-v1-app-override-rules-id
      parameters:
      - $ref: '#/components/parameters/uuid-required'
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                - items:
                    $ref: '#/components/schemas/app-override-rules'
                  type: array
          description: Get the remote network by id.
        '400':
          $ref: '#/components/responses/bad_request_errors_basic'
        '401':
          $ref: '#/components/responses/auth_errors'
        '403':
          $ref: '#/components/responses/access_errors'
        '404':
          $ref: '#/components/responses/not_found'
        default:
          $ref: '#/components/responses/default_errors'
      security:
      - Bearer: []
      summary: Get an application override rule by ID
      tags:
      - ApplicationOverrideRules
    put:
      description: 'Edit an [application](https://docs.paloaltonetworks.com/network-security/security-policy/objects/applications)
        override rule.

        '
      operationId: put-sse-config-v1-app-override-rules-id
      parameters:
      - $ref: '#/components/parameters/uuid-required'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/app-override-rules'
        description: The app override policy rule you want to edit
      responses:
        '200':
          $ref: '#/components/responses/http_ok'
        '400':
          $ref: '#/components/responses/bad_request_errors_basic_with_body'
        '401':
          $ref: '#/components/responses/auth_errors'
        '403':
          $ref: '#/components/responses/access_errors'
        '404':
          $ref: '#/components/responses/not_found'
        '409':
          $ref: '#/components/responses/conflict_errors'
        default:
          $ref: '#/components/responses/default_errors'
      security:
      - Bearer: []
      summary: Edit an application override rule
      tags:
      - ApplicationOverrideRules
servers:
- url: https://api.sase.paloaltonetworks.com
tags:
- name: ApplicationOverrideRules
