components:
  schemas:
    Error:
      properties:
        _error:
          items:
            $ref: '#/components/schemas/ErrorResponse'
          type: array
    ErrorResponse:
      properties:
        code:
          type: string
        message:
          type: string
    ListQueryResponse:
      properties:
        count:
          description: 'The actual count.

            '
          format: int32
          type: integer
        deleted_count:
          description: 'The deleted number.

            '
          format: int64
          type: integer
        deleted_ids:
          description: 'The deleted IDs.

            '
          items:
            type: string
          type: array
        description:
          description: 'Description of the query. Max size = 256.

            '
        id:
          description: 'The ID.

            '
          type: string
        next_query:
          description: 'Details of the next query.

            '
          type: object
        total_count:
          description: 'Total number.

            '
          format: int64
          type: integer
      type: object
    PrismaAccessConfig:
      properties:
        id:
          description: Id
          type: string
        remote_networks:
          description: 'Remote Networks: Valid Valid '
          items:
            $ref: '#/components/schemas/RemoteNetwork'
          type: array
        site_id:
          description: 'Site Id: Digits(fraction = 0, integer = 50, SITEID_INVALID)
            NotNull '
          type: string
      required:
      - site_id
    PrismaAccessConfigQueryResponse:
      properties:
        id:
          description: Id
          type: string
        remote_networks:
          description: 'Remote Networks: Valid Valid '
          items:
            $ref: '#/components/schemas/RemoteNetwork'
          type: array
        site_id:
          description: 'Site Id: Digits(fraction = 0, integer = 50, SITEID_INVALID)
            NotNull '
          type: string
      required:
      - site_id
    RemoteNetwork:
      properties:
        remote_network_names:
          description: Remote Network Names
          items:
            description: Remote Network Names
            type: string
          type: array
        spn_name:
          description: 'Spn Name: NotNull(error = DEM_INVALID_SPN_NAME: Security processing
            name is not specified) '
          type: string
      required:
      - spn_name
info:
  contact: {}
  description: No description available.
  title: Prisma Access Configs
  version: Latest
openapi: 3.0.0
paths:
  /sdwan/v2.0/api/prismaaccess_configs/query:
    post:
      description: Query Prisma Access config
      operationId: post-sdwan-v2.0-api-prismaaccess_configs-query
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PrismaAccessConfigQueryResponse'
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/ListQueryResponse'
                - properties:
                    items:
                      items:
                        $ref: '#/components/schemas/PrismaAccessConfigQueryResponse'
                      type: array
                  type: object
          description: Successful operation
      summary: Query Prisma Access config (v2.0)
      tags:
      - Prisma Access Configs
  /sdwan/v2.0/api/sites/{site_id}/prismaaccess_configs:
    get:
      description: Get all Prisma Access Configs for a site
      operationId: get-sdwan-v2.0-api-sites-site_id-prismaaccess_configs
      parameters:
      - description: Site Id
        in: path
        name: site_id
        required: true
        schema:
          description: Site Id
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/ListQueryResponse'
                - properties:
                    items:
                      items:
                        $ref: '#/components/schemas/PrismaAccessConfig'
                      type: array
                  type: object
          description: Successful operation
        '400':
          content:
            application/json:
              example:
                value:
                  _error:
                  - code: SITE_NOT_FOUND
              schema:
                $ref: '#/components/schemas/Error'
          description: Bad Request
      summary: Get all Prisma Access Configs for a site (v2.0)
      tags:
      - Prisma Access Configs
    post:
      description: Create a Prisma Access Config with remote networks and security
        processing node
      operationId: post-sdwan-v2.0-api-sites-site_id-prismaaccess_configs
      parameters:
      - description: Site Id
        in: path
        name: site_id
        required: true
        schema:
          description: Site Id
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PrismaAccessConfig'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PrismaAccessConfig'
          description: Successful operation
        '400':
          content:
            application/json:
              example:
                value:
                  _error:
                  - code: INVALID_JSON_INPUT
                  - code: INVALID_JSON_EXTRA_ATTRIBUTE
                  - code: SITE_NOT_FOUND
                  - code: DEM_PA_CONFIG_EXISTS
              schema:
                $ref: '#/components/schemas/Error'
          description: Bad Request
      summary: Create a Prisma Access Config with remote networks and security processing
        node (v2.0)
      tags:
      - Prisma Access Configs
  /sdwan/v2.0/api/sites/{site_id}/prismaaccess_configs/{config_id}:
    delete:
      description: Delete a Prisma Access Config with remote networks and security
        processing nodev2.0/api/tenants/:tenant_id/sites/:site_id/prismaaccess_configs/:config_id
      operationId: delete-sdwan-v2.0-api-sites-site_id-prismaaccess_configs-config_id
      parameters:
      - description: Site Id
        in: path
        name: site_id
        required: true
        schema:
          description: Site Id
          type: string
      - description: Prisma Access Config
        in: path
        name: config_id
        required: true
        schema:
          description: Config Id
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PrismaAccessConfig'
          description: Successful operation
        '400':
          content:
            application/json:
              example:
                value:
                  _error:
                  - code: INVALID_JSON_INPUT
                  - code: INVALID_JSON_EXTRA_ATTRIBUTE
                  - code: SITE_NOT_FOUND
                  - code: INVALID_JSON_COMMON_ATTR_MISMATCH
                  - code: INVALID_REQUEST_DUPLICATE_KEY
              schema:
                $ref: '#/components/schemas/Error'
          description: Bad Request
      summary: Delete a Prisma Access Config with remote networks and security processing
        node (v2.0)
      tags:
      - Prisma Access Configs
    get:
      description: Get A Prisma Access Configs for a site
      operationId: get-sdwan-v2.0-api-sites-site_id-prismaaccess_configs-config_id
      parameters:
      - description: Site Id
        in: path
        name: site_id
        required: true
        schema:
          description: Site Id
          type: string
      - description: Config Id
        in: path
        name: config_id
        required: true
        schema:
          description: Config Id
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PrismaAccessConfig'
          description: Successful operation
        '400':
          content:
            application/json:
              example:
                value:
                  _error:
                  - code: SITE_NOT_FOUND
              schema:
                $ref: '#/components/schemas/Error'
          description: Bad Request
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Bad Request
      summary: Get A Prisma Access Configs for a site (v2.0)
      tags:
      - Prisma Access Configs
    put:
      description: Update a Prisma Access Config with remote networks and security
        processing node
      operationId: put-sdwan-v2.0-api-sites-site_id-prismaaccess_configs-config_id
      parameters:
      - description: Site Id
        in: path
        name: site_id
        required: true
        schema:
          description: Site Id
          type: string
      - description: Prisma Access Config
        in: path
        name: config_id
        required: true
        schema:
          description: Config Id
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PrismaAccessConfig'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PrismaAccessConfig'
          description: Successful operation
        '400':
          content:
            application/json:
              example:
                value:
                  _error:
                  - code: INVALID_JSON_INPUT
                  - code: INVALID_JSON_EXTRA_ATTRIBUTE
                  - code: SITE_NOT_FOUND
                  - code: INVALID_JSON_COMMON_ATTR_MISMATCH
                  - code: INVALID_REQUEST_DUPLICATE_KEY
              schema:
                $ref: '#/components/schemas/Error'
          description: Bad Request
      summary: Update a Prisma Access Config with remote networks and security processing
        node (v2.0)
      tags:
      - Prisma Access Configs
servers:
- url: https://api.sase.paloaltonetworks.com
tags:
- name: Prisma Access Configs
