components:
  schemas:
    Error:
      properties:
        _error:
          items: {$ref: '#/components/schemas/ErrorResponse'}
          type: array
    ErrorResponse:
      properties:
        code: {description: 'The error code.

            ', type: string}
        message: {description: 'The error message.

            ', type: string}
    ListQueryResponse:
      properties:
        count: {description: 'The actual count.

            ', format: int32, type: integer}
        deleted_count: {description: 'The deleted number.

            ', format: int64, type: integer}
        deleted_ids:
          description: 'The deleted IDs.

            '
          items: {type: string}
          type: array
        description: {description: 'Description of the query. Max size = 256.

            '}
        id: {description: 'The ID.

            ', type: string}
        next_query: {description: 'Details of the next query.

            ', type: object}
        total_count: {description: 'Total number.

            ', format: int64, type: integer}
      type: object
    PrismaAccessConfig:
      properties:
        id: {description: 'The ID of the prisma access configs.

            ', type: string}
        remote_networks:
          description: 'The details of the prisma access configuration remote networks.

            '
          items: {$ref: '#/components/schemas/RemoteNetwork'}
          type: array
        site_id: {description: 'The site ID of the prisma access configs.

            ', type: string}
      required: [site_id]
    PrismaAccessConfigQueryResponse:
      properties:
        id: {description: 'The ID of the prisma access configs.

            ', type: string}
        remote_networks:
          description: 'The details of the prisma access configuration remote networks.

            '
          items: {$ref: '#/components/schemas/RemoteNetwork'}
          type: array
        site_id: {description: 'The site ID of the prisma access configs.

            ', type: string}
      required: [site_id]
    RemoteNetwork:
      properties:
        edge_location_display: {description: 'Edge Location Display: JsonIgnore(value
            = true) ', type: string}
        edge_location_value: {description: 'Edge Location Value: JsonIgnore(value
            = true) ', type: string}
        remote_network_names:
          description: 'The names of the remote networks.

            '
          items: {description: Remote Network Names, type: string}
          type: array
        service_link_ids:
          description: 'Service Link Ids: JsonIgnore(value = true) '
          items: {description: Service Link Ids, type: string}
          type: array
        spn_name: {description: 'The SPN (Security Processing Name) of the prisma
            access config.

            ', type: string}
info:
  contact: {}
  description: List of APIs that are used for Prisma Access configuration.
  title: Prisma Access Configs
  version: Latest
openapi: 3.0.0
paths:
  /sdwan/v2.0/api/prismaaccess_configs/query:
    post:
      description: Query the Prisma Access configurations.
      operationId: post-sdwan-v2.0-api-prismaaccess_configs-query
      requestBody:
        content:
          application/json:
            schema: {$ref: '#/components/schemas/PrismaAccessConfigQueryResponse'}
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                - {$ref: '#/components/schemas/ListQueryResponse'}
                - properties:
                    items:
                      items: {$ref: '#/components/schemas/PrismaAccessConfigQueryResponse'}
                      type: array
                  type: object
          description: Successful operation
      summary: Query Prisma Access Configs (v2.0)
      tags: [Prisma Access Configs]
  /sdwan/v2.0/api/sites/{site_id}/prismaaccess_configs:
    get:
      description: List all all Prisma Access configurations for a site.
      operationId: get-sdwan-v2.0-api-sites-site_id-prismaaccess_configs
      parameters:
      - description: The ID of the site.
        in: path
        name: site_id
        required: true
        schema: {description: Site Id, type: string}
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                - {$ref: '#/components/schemas/ListQueryResponse'}
                - properties:
                    items:
                      items: {$ref: '#/components/schemas/PrismaAccessConfig'}
                      type: array
                  type: object
          description: Successful operation
        '400':
          content:
            application/json:
              example:
                value:
                  _error:
                  - {code: SITE_NOT_FOUND}
              schema: {$ref: '#/components/schemas/Error'}
          description: Bad Request
      summary: Get Prisma Access Configs for a Site (v2.0)
      tags: [Prisma Access Configs]
    post:
      description: Create a Prisma Access configuration with remote networks and the
        security processing node.
      operationId: post-sdwan-v2.0-api-sites-site_id-prismaaccess_configs
      parameters:
      - description: The ID of the site.
        in: path
        name: site_id
        required: true
        schema: {description: Site Id, type: string}
      requestBody:
        content:
          application/json:
            schema: {$ref: '#/components/schemas/PrismaAccessConfig'}
      responses:
        '200':
          content:
            application/json:
              schema: {$ref: '#/components/schemas/PrismaAccessConfig'}
          description: Successful operation
        '400':
          content:
            application/json:
              example:
                value:
                  _error:
                  - {code: INVALID_JSON_INPUT}
                  - {code: INVALID_JSON_EXTRA_ATTRIBUTE}
                  - {code: SITE_NOT_FOUND}
                  - {code: DEM_PA_CONFIG_EXISTS}
              schema: {$ref: '#/components/schemas/Error'}
          description: Bad Request
      summary: Create Prisma Access Config with Remote Networks (v2.0)
      tags: [Prisma Access Configs]
  /sdwan/v2.0/api/sites/{site_id}/prismaaccess_configs/{config_id}:
    delete:
      description: Delete a Prisma Access configuration with remote networks and the
        security processing node.
      operationId: delete-sdwan-v2.0-api-sites-site_id-prismaaccess_configs-config_id
      parameters:
      - description: The ID of the site.
        in: path
        name: site_id
        required: true
        schema: {description: Site Id, type: string}
      - description: The ID of the prisma access config.
        in: path
        name: config_id
        required: true
        schema: {description: Config Id, type: string}
      responses:
        '200':
          content:
            application/json:
              schema: {$ref: '#/components/schemas/PrismaAccessConfig'}
          description: Successful operation
        '400':
          content:
            application/json:
              example:
                value:
                  _error:
                  - {code: INVALID_JSON_INPUT}
                  - {code: INVALID_JSON_EXTRA_ATTRIBUTE}
                  - {code: SITE_NOT_FOUND}
                  - {code: INVALID_JSON_COMMON_ATTR_MISMATCH}
                  - {code: INVALID_REQUEST_DUPLICATE_KEY}
              schema: {$ref: '#/components/schemas/Error'}
          description: Bad Request
      summary: Delete Prisma Access Config with Remote Networks (v2.0)
      tags: [Prisma Access Configs]
    get:
      description: List the Prisma Access configurations for a site.
      operationId: get-sdwan-v2.0-api-sites-site_id-prismaaccess_configs-config_id
      parameters:
      - description: The ID of the site.
        in: path
        name: site_id
        required: true
        schema: {description: Site Id, type: string}
      - description: The ID of the prisma access config.
        in: path
        name: config_id
        required: true
        schema: {description: Config Id, type: string}
      responses:
        '200':
          content:
            application/json:
              schema: {$ref: '#/components/schemas/PrismaAccessConfig'}
          description: Successful operation
        '400':
          content:
            application/json:
              example:
                value:
                  _error:
                  - {code: SITE_NOT_FOUND}
              schema: {$ref: '#/components/schemas/Error'}
          description: Bad Request
        '404':
          content:
            application/json:
              schema: {$ref: '#/components/schemas/Error'}
          description: Bad Request
      summary: Get Prisma Access Configs for a Site (v2.0)
      tags: [Prisma Access Configs]
    put:
      description: Update a Prisma Access configuration with remote networks and security
        processing node.
      operationId: put-sdwan-v2.0-api-sites-site_id-prismaaccess_configs-config_id
      parameters:
      - description: The ID of the site.
        in: path
        name: site_id
        required: true
        schema: {description: Site Id, type: string}
      - description: The ID of the prisma access config.
        in: path
        name: config_id
        required: true
        schema: {description: Config Id, type: string}
      requestBody:
        content:
          application/json:
            schema: {$ref: '#/components/schemas/PrismaAccessConfig'}
      responses:
        '200':
          content:
            application/json:
              schema: {$ref: '#/components/schemas/PrismaAccessConfig'}
          description: Successful operation
        '400':
          content:
            application/json:
              example:
                value:
                  _error:
                  - {code: INVALID_JSON_INPUT}
                  - {code: INVALID_JSON_EXTRA_ATTRIBUTE}
                  - {code: SITE_NOT_FOUND}
                  - {code: INVALID_JSON_COMMON_ATTR_MISMATCH}
                  - {code: INVALID_REQUEST_DUPLICATE_KEY}
              schema: {$ref: '#/components/schemas/Error'}
          description: Bad Request
      summary: Update Prisma Access Config with Remote Networks (v2.0)
      tags: [Prisma Access Configs]
servers:
- {url: 'https://api.sase.paloaltonetworks.com'}
tags:
- {name: Prisma Access Configs}
